service: IWIBotBackend

provider:
  name: openwhisk

package:
  name: IWIBot
  individually: true
  exclude:
    - '**/*'

triggers:

plugins:
  - iwibot-serverless-build-plugin # for building nodejs actions


functions:
  Joke:
    name: Joke
    runtime: nodejs:8
    handler: lib/Joke.main
    package:
      name: nodejs-joke
      include:
        - 'lib/**/*'
        - package.json
        - README.md