service: IWIBotBackend
provider:
  name: openwhisk
package:
  name: IWIBot
  individually: true
  exclude:
    - '**/*'
triggers: null
plugins:
  - iwibot-serverless-build-plugin
functions:
  Schwimmbad:
    enabled: false
    name: Schwimmbad
    runtime: java
    handler: de.hska.iwibot.actions.java.Schwimmbad
    package:
      name: java-schwimmbad
      include:
        - src/**/*
        - pom.xml
        - README.md
    annotations:
      web-export: true
  Joke:
    enabled: false
    name: Joke
    runtime: 'nodejs:8'
    handler: lib/Joke.main
    package:
      name: nodejs-joke
      include:
        - lib/**/*
        - package.json
        - README.md
  Bescheinigung:
    enabled: false
    name: Bescheinigung
    runtime: 'nodejs:8'
    handler: lib/Bescheinigung.main
    package:
      name: nodejs-bescheinigung
      include:
        - lib/**/*
        - package.json
        - README.md
  Meal:
    enabled: false
    name: Meal
    runtime: 'nodejs:8'
    handler: lib/Meal.main
    package:
      name: nodejs-meal
      include:
        - lib/**/*
        - package.json
        - README.md
  Router:
    enabled: false
    name: Router
    runtime: 'nodejs:8'
    handler: lib/Router.main
    bind:
      - service:
          name: conversation
          instance: conversation
    annotations:
      web-export: true
    events:
      - http:
          action: Router
          basepath: iwibot
          relpath: router
          operation: post
          response-type: http
          cors: true
    package:
      name: nodejs-router
      include:
        - lib/**/*
        - package.json
        - README.md
  Semester:
    enabled: false
    name: Semester
    runtime: 'nodejs:8'
    handler: lib/Semester.main
    package:
      name: nodejs-semester
      include:
        - lib/**/*
        - package.json
        - README.md
  Sprechstunde:
    enabled: false
    name: Sprechstunde
    runtime: 'nodejs:8'
    handler: lib/Sprechstunde.main
    package:
      name: nodejs-sprechstunde
      include:
        - lib/**/*
        - package.json
        - README.md
  Timetable:
    enabled: false
    name: Timetable
    runtime: 'nodejs:8'
    handler: lib/Timetable.main
    package:
      name: nodejs-timetable
      include:
        - lib/**/*
        - package.json
        - README.md
  Weather:
    enabled: false
    name: Weather
    runtime: 'nodejs:8'
    handler: lib/Weather.main
    bind:
      - service:
          name: weatherinsights
          instance: weatherinsights
    package:
      name: nodejs-weather
      include:
        - lib/**/*
        - package.json
        - README.md
  Wikipedia:
    enabled: false
    name: Wikipedia
    runtime: 'nodejs:8'
    handler: lib/Wikipedia.main
    package:
      name: nodejs-wikipedia
      include:
        - lib/**/*
        - package.json
        - README.md
  Modulhandbuch:
    enabled: false
    name: Modulhandbuch
    runtime: 'nodejs:8'
    handler: lib/Modulhandbuch.main
    package:
      name: nodejs-modulhandbuch
      include:
        - lib/**/*
        - package.json
        - README.md
  Template-PHP:
    enabled: false
    name: Template-PHP
    runtime: 'php:7.2'
    handler: lib/index.main
    package:
      name: template-php
      include:
        - lib/**/*
        - vendor/**/*
        - composer.json
        - README.md
  Template-Go:
    enabled: false
    name: Template-Go
    runtime: blackbox
    kind: go
    handler: bin/exec
    package:
      name: template-go
      include:
        - bin/exec
  Template-Python:
    enabled: false
    name: Template-Python
    runtime: 'python:3'
    handler: lib/__main__.main
    package:
      name: template-python
      include:
        - lib/**/*
        - requirements.txt
        - README.md